"""Static joint definitions."""

mocap_joints_name_to_index = {
    "PELVIS": 0,
    "C_ASIS": 1,
    "SACR": 2,
    "C_HIP": 3,
    "RASI": 4,
    "RPSI": 5,
    "RHIP": 6,
    "RTRO": 7,
    "RTHI": 8,
    "RKNE": 9,
    "RKNM": 10,
    "RKNL": 11,
    "R_Medial Tibial Condyle": 12,
    "R_Lateral Tibial Condyle": 13,
    "RTIB": 14,
    "RANK": 15,
    "RANM": 16,
    "RANL": 17,
    "RHEL": 18,
    "R_Toe": 19,
    "RBAM": 20,
    "RMT5": 21,
    "LASI": 22,
    "LPSI": 23,
    "LHIP": 24,
    "LTRO": 25,
    "LTHI": 26,
    "LKNE": 27,
    "LKNM": 28,
    "LKNL": 29,
    "L_Medial Tibial Condyle": 30,
    "L_Lateral Tibial Condyle": 31,
    "LTIB": 32,
    "LANK": 33,
    "LANM": 34,
    "LANL": 35,
    "LHEL": 36,
    "L_Toe": 37,
    "LBAM": 38,
    "LMT5": 39,
    "Xiphoid": 40,
    "T10": 41,
    "RRIB": 42,
    "LRIB": 43,
    "Manubrium": 44,
    "CLAV": 45,
    "C7": 46,
    "EARC": 47,
    "Nasion": 48,
    "BHED": 49,
    "REAR": 50,
    "LEAR": 51,
    "Vertex": 52,
    "L_Shoulder Joint": 53,
    "LSHO": 54,
    "LSHF": 55,
    "LSHB": 56,
    "LUPA": 57,
    "LELB": 58,
    "LFRA": 59,
    "LELL": 60,
    "LELM": 61,
    "LWRT": 62,
    "LWSL": 63,
    "LWSM": 64,
    "LHND": 65,
    "LMP2": 66,
    "LMP5": 67,
    "R_Shoulder Joint": 68,
    "RSHO": 69,
    "RSHF": 70,
    "RSHB": 71,
    "RUPA": 72,
    "RELB": 73,
    "RFRA": 74,
    "RELL": 75,
    "RELM": 76,
    "RWRT": 77,
    "RWSL": 78,
    "RWSM": 79,
    "RHND": 80,
    "RMP2": 81,
    "RMP5": 82,
    "RHIP_Z": 83,
}

hj_mocap_joints_name_to_index = {
    "RHND": 0,
    "RWRL": 1,
    "RWRM": 2,
    "RWST": 3,
    "RELL": 4,
    "RELM": 5,
    "RSHA": 6,
    "RELB": 7,
    "RshoulderC": 8,
    "LHND": 9,
    "LWRL": 10,
    "LWRM": 11,
    "LWST": 12,
    "LELL": 13,
    "LELM": 14,
    "LSHA": 15,
    "LELB": 16,
    "LshoulderC": 17,
    "RTOE": 18,
    "RBAL": 19,
    "RBAM": 20,
    "RHEL": 21,
    "RankleC": 22,
    "RANL": 23,
    "RANM": 24,
    "RkneeC": 25,
    "RKNL": 26,
    "RKNM": 27,
    "LTOE": 28,
    "LBAL": 29,
    "LBAM": 30,
    "LHEL": 31,
    "LankleC": 32,
    "LANL": 33,
    "LANM": 34,
    "LkneeC": 35,
    "LKNL": 36,
    "LKNM": 37,
    "STEF": 38,
    "C7": 39,
    "XIPF": 40,
    "T8": 41,
    "NeckC": 42,
    "T12": 43,
    "RRIB": 44,
    "LRIB": 45,
    "ThoracicJC": 46,
    "Front_HEAD": 47,
    "Top_HEAD": 48,
    "REAR": 49,
    "LEAR": 50,
    "RASI": 51,
    "LASI": 52,
    "RPSI": 53,
    "LPSI": 54,
    "RtopILUM": 55,
    "LtopILUM": 56,
    "RhipC": 57,
    "LhipC": 58,
    "LumbarJC": 59,
    "Prox": 60,
    "ProxGround": 61,
    "Dist": 62,
    "DistGround": 63,
}

h36m_joints_name_to_index = {
    "PELVIS": 0,
    "R_HIP": 1,
    "R_KNEE": 2,
    "R_ANKLE": 3,
    "L_HIP": 4,
    "L_KNEE": 5,
    "L_ANKLE": 6,
    "SPINE": 7,
    "THORAX": 8,
    "NECK": 9,
    "HEAD": 10,
    "L_SHOULDER": 11,
    "L_ELBOW": 12,
    "L_WRIST": 13,
    "R_SHOULDER": 14,
    "R_ELBOW": 15,
    "R_WRIST": 16,
}

joint_index_h36m_to_mocap = {
    0: [mocap_joints_name_to_index["PELVIS"]],
    1: [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RPSI"]],
    2: [mocap_joints_name_to_index["RKNE"]],
    3: [mocap_joints_name_to_index["RANK"]],
    4: [mocap_joints_name_to_index["LASI"], mocap_joints_name_to_index["LPSI"]],
    5: [mocap_joints_name_to_index["LKNE"]],
    6: [mocap_joints_name_to_index["LANK"]],
    7: [mocap_joints_name_to_index["Xiphoid"], mocap_joints_name_to_index["T10"]],
    8: [mocap_joints_name_to_index["CLAV"]],
    9: [mocap_joints_name_to_index["CLAV"], mocap_joints_name_to_index["Nasion"]],
    10: [mocap_joints_name_to_index["Vertex"], mocap_joints_name_to_index["EARC"]],
    11: [mocap_joints_name_to_index["L_Shoulder Joint"]],
    12: [mocap_joints_name_to_index["LELB"]],
    13: [mocap_joints_name_to_index["LWRT"]],
    14: [mocap_joints_name_to_index["R_Shoulder Joint"]],
    15: [mocap_joints_name_to_index["RELB"]],
    16: [mocap_joints_name_to_index["RWRT"]],
}

joint_index_h36m_to_hj_mocap = {
    0: [hj_mocap_joints_name_to_index["LumbarJC"]],
    1: [hj_mocap_joints_name_to_index["RhipC"]],
    2: [hj_mocap_joints_name_to_index["RkneeC"]],
    3: [hj_mocap_joints_name_to_index["RankleC"]],
    4: [hj_mocap_joints_name_to_index["LhipC"]],
    5: [hj_mocap_joints_name_to_index["LkneeC"]],
    6: [hj_mocap_joints_name_to_index["LankleC"]],
    7: [hj_mocap_joints_name_to_index["T8"]],
    8: [hj_mocap_joints_name_to_index["C7"]],
    9: [hj_mocap_joints_name_to_index["REAR"], hj_mocap_joints_name_to_index["LEAR"]],
    10: [hj_mocap_joints_name_to_index["Top_HEAD"]],
    11: [hj_mocap_joints_name_to_index["LSHA"]],
    12: [hj_mocap_joints_name_to_index["LELB"]],
    13: [hj_mocap_joints_name_to_index["LWST"]],
    14: [hj_mocap_joints_name_to_index["RSHA"]],
    15: [hj_mocap_joints_name_to_index["RELB"]],
    16: [hj_mocap_joints_name_to_index["RWST"]],
}

joint_index_coco_to_mocap = {
    0: [mocap_joints_name_to_index["CLAV"], mocap_joints_name_to_index["Nasion"]],
    1: [],
    2: [],
    3: [],
    4: [],
    5: [mocap_joints_name_to_index["L_Shoulder Joint"]],
    6: [mocap_joints_name_to_index["R_Shoulder Joint"]],
    7: [mocap_joints_name_to_index["LELB"]],
    8: [mocap_joints_name_to_index["RELB"]],
    9: [mocap_joints_name_to_index["LWRT"]],
    10: [mocap_joints_name_to_index["RWRT"]],
    11: [mocap_joints_name_to_index["LASI"], mocap_joints_name_to_index["LPSI"]],
    12: [mocap_joints_name_to_index["RASI"], mocap_joints_name_to_index["RPSI"]],
    13: [mocap_joints_name_to_index["LKNE"]],
    14: [mocap_joints_name_to_index["RKNE"]],
    15: [mocap_joints_name_to_index["LANK"]],
    16: [mocap_joints_name_to_index["RANK"]],
}

joint_index_coco_to_mocap_v2 = {
    0: [mocap_joints_name_to_index["Nasion"]],
    1: [],  # left_eye - interpolated
    2: [],  # right_eye - interpolated
    3: [mocap_joints_name_to_index["LEAR"]],
    4: [mocap_joints_name_to_index["REAR"]],
    5: [mocap_joints_name_to_index["L_Shoulder Joint"]],
    6: [mocap_joints_name_to_index["R_Shoulder Joint"]],
    7: [mocap_joints_name_to_index["LELB"]],
    8: [mocap_joints_name_to_index["RELB"]],
    9: [mocap_joints_name_to_index["LWRT"]],
    10: [mocap_joints_name_to_index["RWRT"]],
    11: [mocap_joints_name_to_index["LHIP"]],
    12: [mocap_joints_name_to_index["RHIP"]],
    13: [mocap_joints_name_to_index["LKNE"]],
    14: [mocap_joints_name_to_index["RKNE"]],
    15: [mocap_joints_name_to_index["LANK"]],
    16: [mocap_joints_name_to_index["RANK"]],
}
